### ISSUE TITLE
Operation failed with ATT error: 0x0e (Unlikely Error)

### ISSUE THREAD

**Issue by kiricheglov** [zyv/huawei-lpv2#10]
Hello everyone again! I was finally able to hook up to the watch, but code gives an authentication error, I looked at the logs in wireshark and found such a line
![изображение](https://user-images.githubusercontent.com/123584220/219956476-f3e414ad-0fe9-4331-b0ca-7bf5f71e0e25.png)
after the watch send an authentication error
![изображение](https://user-images.githubusercontent.com/123584220/219956554-6bfb515e-e029-4624-b489-f67b1670949e.png)
in the watch logs I found a string with authentication, but does not coincide with the authentication request in the script, what should I do?
![изображение](https://user-images.githubusercontent.com/123584220/219956659-84551250-366a-4232-a742-54493d3d5353.png)
![изображение](https://user-images.githubusercontent.com/123584220/219956682-c69ab734-2ebc-42d1-a365-f87f55b872f6.png)

**Comment by zyv** [comment]
You didn't say how exactly you are connecting to the watch and how are you decoding the dumps using Wireshark, but I assume you are using the code from this repository together with the Wireshark-related code from @psolyca & @MartinJM .

I have already told you that this code probably doesn't support the newer authentication protocol used by your watch, and I'm unable to support you with getting it to work.

If you need help you'd better post into the GadgetBridge development thread if you are using Java implementation:

https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/2462

... or talk to the team on Matrix.

All I can do here is to review / accept high quality Python code and/or documentation.
