### ISSUE TITLE
Testing on Honor Band 3 NYX-B10

### ISSUE THREAD

**Issue by denics** [zyv/huawei-lpv2#2]
Hi @zyv I am testing your console with my honor band 3 to see if I can help with the integration with gadgetbridge. Unfortunately I am unable to do anything and I get this error:

```
./Git/huawei-lpv2# python3 band_gatt.py 
INFO:bleak.backends.bluezdbus.discovery:xx:xx:xx:xx:xx:xx,xx:xx:xx:xx:xx:xx (-57 dBm), Object Path: /org/bluez/hci0/dev_xx:xx:xx:xx:xx:xx
INFO:bleak.backends.bluezdbus.discovery:xx:xx:xx:xx:xx:xx, xx:xx:xx:xx:xx:xx (-91 dBm), Object Path: /org/bluez/hci0/dev_xx:xx:xx:xx:xx:xx
INFO:bleak.backends.bluezdbus.discovery:xx:xx:xx:xx:xx:xx, xx:xx:xx:xx:xx:xx (-62 dBm), Object Path: /org/bluez/hci0/dev_xx:xx:xx:xx:xx:xx
DEBUG:bleak.backends.bluezdbus.client:Connecting to BLE device @ xx:xx:xx:xx:xx:xx with hci0
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/bleak/backends/bluezdbus/client.py", line 124, in connect
    ).asFuture(self.loop)
txdbus.error.RemoteError: org.freedesktop.DBus.Error.UnknownObject: Method "Connect" with signature "" on interface "org.bluez.Device1" doesn't exist
```
Any hint?

Thanks

**Comment by denics** [comment]
I forgot to say that I am using a Debian laptop and the honor band firmware is 1.5.53

**Comment by zyv** [comment]
Hi @denics, I think that you are the first one to try this on Linux (using the BlueZ backend), and thus you've just hit the bug in the Bluetooth client library that I'm using: hbldh/bleak#150 . I developed my library on macOS and others have tested it on Windows - pairing is not actually required, and connection still works for bands, which haven't updated the handshake process.

I'm not sure how I can help - I'm under extreme time pressure right now, so can only make some suggestions for you to explore:

* You can try to talk to Bleak people and see if you can help them with the issue
* You can try to abstract Bleak from my code, and add support for some other library, which would work with BlueZ

As I was looking for a Bluetooth client library, unfortunately, Bleak was the only one I found to be remotely usable. There are also some others, but they are either unmaintained, or incomplete, or not cross-platform, or everything at the same time.

* https://github.com/IanHarvey/bluepy
* https://github.com/adafruit/Adafruit_Python_BluefruitLE
* https://github.com/peplin/pygatt

I think in as far as BlueZ is concerned, bluepy should work best, so you could just write a small async wrapper class that mimics Bleak interface and drop it in, to see if you can get any further with that... I'm only using some very few rudimentary functions, so it shouldn't take much time.

Hope that helps!

**Comment by denics** [comment]
Thank you @zyv , i'll try to explore both of your suggestions. I would really like to use gadgetbridge with my device.

**Comment by zyv** [comment]
Hi @denics , if your end goal is to extend GadgetBridge and you are okay with Java, then maybe it will be easier for you to start rebuilding my library on top of the GadgetBridge infrastructure. The only problem is that Huawei has changed the handshake, so it has to be reverse engineered again and just porting my code 1:1 will not bring you too far.

My goal was to study the protocol first, and then create a tool that can be used on any computer, not only Android smartphones. Therefore I took Python as a fast prototyping language. But as you can see, it has some downsides too - like very sad state of support for BLE development. If you are well familiar with Android development infrastructure, then maybe it will be easier for you to build a prototype using that instead.

Just make sure to document your findings :) or maybe you could even use my wiki for your efforts...

**Comment by denics** [comment]
Thanks for the lead! Indeed if I find the time to reverse engineer the handshake I will put my findings in here.

**Comment by zyv** [comment]
I'm closing this since the initial question has been answered, please feel free to ask again if there is anything I can help you with.

**Comment by zyv** [comment]
@denics check this out - https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/2462 - @psolyca and his team did an excellent job further reversing stuff and integrating it into GB.
